JamConnection: turn FourCC into a struct
The genered JamConnection moc code fails to compile:

  /usr/include/qt6/QtCore/qtypeinfo.h:198:81: error: comparison between two arrays [-Werror=array-compare]
  198 | struct has_operator_equal<T, std::void_t<decltype(bool(std::declval<const T&>() == std::declval<const T&>()))>>
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

This is due to FourCC being an array. Make it a struct with an array
field to solve the issue.

Signed-off-by: Stefan Hajnoczi <stefanha@jammr.net>