AppView: add missing <inttypes.h> header for PRId64 on macOS
On macOS the <inttypes.h> header must be included to get PRId64. This
fixes a CI failure:

  ../core/AppView.cpp:50:36: error: expected ')'
            qWarning("%s called %" PRId64 " ns after last time", __func__, duration);

Signed-off-by: Stefan Hajnoczi <stefanha@jammr.net>